replication:
  connections:
    - type: postgresql
      uri: ${POWERSYNC_DATABASE_URL}
      sslmode: disable

storage:
  type: postgresql
  uri: ${POWERSYNC_DATABASE_URL}
  sslmode: disable

sync_config:
  path: /config/sync-config.yaml

client_auth:
  jwks_uri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com
  audience: ['${FIREBASE_PROJECT_ID}']